<a href="https://colab.research.google.com/github/Daarwinmendez/hill_cipher_with_python/blob/main/hill_cipher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sympy as sp
import numpy as np
import math


In [2]:
# Definamos nuestro alfabeto.
caracteres = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzáéíóú ¿?.,;:!¡"
modulo = len(caracteres)
indices = list(range(modulo))
indices_dict = dict(zip(caracteres, indices)) # Creamos un diccionario que almacene el indice de cada elemento
                                                # y tenga las letras como key.

In [3]:
modulo # Quiere decir que 60 será nuestro modulo.

67

Para hacer un cifrado, hay cuatro elementos clave que se deben tener en consideración:

1. Mensaje
2. Código
3. Emisor
4. Receptor

Trabajemos con el cifrado de Hill,  (Hill Cipher)!

### Mensaje

"DISFRUTAR DE UN BUEN LIBRO O UNA PELICULA PUEDE SER MUY RELAJANTE"


O tambien puede ser:

"¡Hola! ¿Cómo estás? Espero que todo esté bien. ¡Disfruta tu día y sigue adelante con ánimo!"

### Codigo

Hagamos seguro que nuestro módulo, sea coprimo con el determinante de la matriz.

In [4]:
def generate_invertible_matrix(shape, modulo, seed):
  """Genera una matriz invertible de forma aleatoria"""

  # Verificamos que la matriz sea cuadrada
  if shape[0] != shape[-1]:
    raise ValueError("La matriz debe ser cuadrada") # Verificamos que la matriz sea cuadrada.
  elif len(shape) != 2:
    raise ValueError("La matriz debe ser de dos dimensiones") # Verificamos que la matriz sea de dos dimensiones.
  elif shape[0] < 2:
    raise ValueError("La matriz debe tener al menos dos dimensiones") # Verificamos que la matriz tenga al menos dos dimensiones.
  elif shape[0] == 0 or shape[-1] == 0:
    raise ValueError("La matriz no debe tener una forma/tamaño de 0") # Verificamoos que la forma no tenga ceros como argumentos.
  else:
    # Generamos una matriz aleatoria de la forma especificada
    # y verificamos si es invertible

    np.random.seed(seed);
    while True:
      matriz = (np.random.randint(10, size=shape))
      det = int(np.linalg.det(matriz))
      mcd = int(math.gcd(det, modulo))
      if det !=0 and mcd == 1 and all(matr.is_integer() for matr in np.linalg.inv(matriz).flatten()) :
        return matriz


In [5]:
# Obtenemos una matriz invertible con la funcion que creamos
matriz_sp = generate_invertible_matrix((4,4),modulo,43)
matriz_sp
#matriz_np = np.array(matriz_sp) # en caso de que halla problema lidiando con los tipos de datos de ambos.

array([[5, 2, 0, 1],
       [2, 4, 7, 0],
       [5, 3, 3, 1],
       [1, 3, 6, 0]])

In [6]:
matriz_sp

array([[5, 2, 0, 1],
       [2, 4, 7, 0],
       [5, 3, 3, 1],
       [1, 3, 6, 0]])

In [7]:
matriz_sp= sp.Matrix(matriz_sp)
matriz_np = np.array(matriz_sp)

matriz_sp.inv()


Matrix([
[-3,  3,  3, -5],
[ 5, -3, -5,  6],
[-2,  1,  2, -2],
[ 6, -9, -5, 13]])

In [8]:
print("Determinante: ", matriz_sp.det())

Determinante:  1


In [9]:
# Asumamos que el emisor quiera enviar un mensaje.

mensaje = "¡Hola! ¿Cómo estás? Espero que todo esté bien. ¡Disfruta tu día y sigue adelante con ánimo!"


Creemos la matriz con el mensaje

In [10]:
matriz_mensaje = [];

for character in mensaje:
  for ind in indices_dict:
    if character == ind:
      matriz_mensaje.append(indices_dict[ind])


In [11]:
# Posición del elemento " ", o espacio.
espacio_pos = indices_dict[" "]

if len(matriz_mensaje) % matriz_sp.shape[0] != 0:
  # Si el modulo 4 de la longitud del mensaje no es exactamente 0, pues añade un caracter "", las veces que falte.
  for i in range(matriz_sp.shape[0] - (len(matriz_mensaje) % matriz_sp.shape[0])):
    matriz_mensaje.append(int(espacio_pos))
else:
  pass

In [12]:
# Aqui trasponemos la matriz mensaje, para dividirlas en filas de 23 columnas, o M columnas,  y la cantidad de filas que tiene nuestra matriz llave.
mensaje_vectorizado = np.array(np.array(matriz_mensaje).T).reshape(matriz_sp.shape[0], -1)


In [13]:
# Visualizando.

mensaje_vectorizado

mensaje_vectorizado[0],
mensaje_vectorizado[1],
mensaje_vectorizado[3]

array([47, 31, 58, 27, 30, 31, 38, 27, 40, 46, 31, 58, 29, 41, 40, 58, 53,
       40, 35, 39, 41, 65, 58])

In [14]:
#Visualicemos el mensaje en numeros antes de encriptar
mensaje_vectorizado =  sp.Matrix(mensaje_vectorizado)
print(mensaje)
mensaje_vectorizado

¡Hola! ¿Cómo estás? Espero que todo esté bien. ¡Disfruta tu día y sigue adelante con ánimo!


Matrix([
[66,  7, 41, 38, 27, 65, 58, 59,  2, 56, 39, 41, 58, 31, 45, 46, 53, 45, 60, 58,  4, 45, 42],
[31, 44, 41, 58, 43, 47, 31, 58, 46, 41, 30, 41, 58, 31, 45, 46, 54, 58, 28, 35, 31, 40, 61],
[58, 66,  3, 35, 45, 32, 44, 47, 46, 27, 58, 46, 47, 58, 30, 55, 27, 58, 51, 58, 45, 35, 33],
[47, 31, 58, 27, 30, 31, 38, 27, 40, 46, 31, 58, 29, 41, 40, 58, 53, 40, 35, 39, 41, 65, 58]])

### Encriptemos el mensaje

In [15]:
mensaje_encriptado = np.dot(matriz_sp, mensaje_vectorizado)
mensaje_encriptado = sp.Matrix(mensaje_encriptado)

In [16]:
print("Mensaje encriptado")
mensaje_encriptado

Mensaje encriptado


Matrix([
[439, 154, 345, 333, 251, 450, 390, 438, 142, 408, 286, 345, 435, 258, 355, 380, 426, 381, 391, 399, 123, 370, 390],
[662, 652, 267, 553, 541, 542, 548, 679, 510, 465, 604, 568, 677, 592, 480, 661, 511, 728, 589, 662, 447, 495, 559],
[644, 396, 395, 496, 429, 593, 553, 637, 326, 530, 490, 524, 634, 463, 490, 591, 561, 613, 572, 608, 289, 515, 550],
[507, 535, 182, 422, 426, 398, 415, 515, 416, 341, 477, 440, 514, 472, 360, 514, 377, 567, 450, 511, 367, 375, 423]])

Este sería el mensaje distorcionado

In [17]:
print(f"Mensaje encriptado con modulo {modulo}")
mensaje_encriptado_mod = mensaje_encriptado % modulo
mensaje_encriptado_mod

Mensaje encriptado con modulo 67


Matrix([
[37, 20, 10, 65, 50, 48, 55, 36,  8,  6, 18, 10, 33, 57, 20, 45, 24, 46, 56, 64, 56, 35, 55],
[59, 49, 66, 17,  5,  6, 12,  9, 41, 63,  1, 32,  7, 56, 11, 58, 42, 58, 53, 59, 45, 26, 23],
[41, 61, 60, 27, 27, 57, 17, 34, 58, 61, 21, 55, 31, 61, 21, 55, 25, 10, 36,  5, 21, 46, 14],
[38, 66, 48, 20, 24, 63, 13, 46, 14,  6,  8, 38, 45,  3, 25, 45, 42, 31, 48, 42, 32, 40, 21]])

Si intentaran interceptar nuestro mensaje esto es lo que obtendrían:

In [37]:
def interceptar_cadena(mensaje_encriptado_mod):
  mensaje_encriptado_letras = []

  for i in mensaje_encriptado_mod:
    for key, value in indices_dict.items():
      if i == value:
        mensaje_encriptado_letras.append(key)


  mensaje_encriptado_letras =  np.array(mensaje_encriptado_letras).reshape(matriz_sp.shape[0], -1)
  print(mensaje_encriptado_letras);


  cadena_cifrada = []
  for i in mensaje_encriptado_letras:
    for j in i:
      cadena_cifrada.append(j)


  return "".join(cadena_cifrada)

cadena_cifrada = interceptar_cadena(mensaje_encriptado_mod);


[['k' 'T' 'K' '!' 'x' 'v' 'í' 'j' 'I' 'G' 'R' 'K' 'g' 'ú' 'T' 's' 'X' 't'
  'ó' ':' 'ó' 'i' 'í']
 ['¿' 'w' '¡' 'Q' 'F' 'G' 'M' 'J' 'o' ';' 'B' 'f' 'H' 'ó' 'L' ' ' 'p' ' '
  'á' '¿' 's' 'Z' 'W']
 ['o' '.' '?' 'a' 'a' 'ú' 'Q' 'h' ' ' '.' 'U' 'í' 'e' '.' 'U' 'í' 'Y' 'K'
  'j' 'F' 'U' 't' 'Ñ']
 ['l' '¡' 'v' 'T' 'X' ';' 'N' 't' 'Ñ' 'G' 'I' 'l' 's' 'D' 'Y' 's' 'p' 'e'
  'v' 'p' 'f' 'n' 'U']]


In [38]:
print(cadena_cifrada)

kTK!xvíjIGRKgúTsXtó:óií¿w¡QFGMJo;BfHóL p á¿sZWo.?aaúQh .Uíe.UíYKjFUtÑl¡vTX;NtÑGIlsDYspevpfnU


### Ahora trabajémos en decifrarla.

1.  Debemos encontrar la inversa de nuestra matriz llave.
2.  Debemos aplicar el modulo de la longitud de la lista de caracteres a la inversa.
3. Luego verificamos si tiene o no, decimales, y eso determinará que haremos para decifrar el mensaje.




In [20]:
# Recuerda que nuestra matriz codificadora era esta.
matriz_sp

Matrix([
[5, 2, 0, 1],
[2, 4, 7, 0],
[5, 3, 3, 1],
[1, 3, 6, 0]])

In [21]:
inversa = matriz_sp.inv()

In [22]:
modulo_inversa = inversa % modulo

modulo_inversa

Matrix([
[64,  3,  3, 62],
[ 5, 64, 62,  6],
[65,  1,  2, 65],
[ 6, 58, 62, 13]])

Mensaje sin que se le aplique el modulo n.



In [23]:
decrypt_sin_modulo = np.dot(modulo_inversa, mensaje_encriptado_mod)

sp.Matrix(decrypt_sin_modulo)

Matrix([
[5024, 5702, 3994, 5532, 4784, 7167, 4413, 5285, 1677, 1128, 1714, 3257, 5016, 4185, 2926, 6009, 4341, 5070, 6827, 6892, 5766, 4936, 4933],
[6731, 7414, 8282, 3207, 2388, 4536, 2175, 3140, 6344, 7880, 1504, 5736, 2805, 7669, 2256, 7617, 4610, 4748, 6192, 4658, 4654, 4931, 2741],
[5016, 5761, 3956, 5596, 4869, 7335, 4466, 5407, 1587,  965, 1733, 3262, 5139, 4078, 2978, 6018, 4382, 5083, 6885, 6959, 5807, 4993, 4991],
[6680, 7602, 8232, 3310, 2576, 4989, 2249, 3444, 6204, 7550, 1572, 5820, 3111, 7411, 2385, 7629, 4676, 4663, 6266, 4662, 4664, 5090, 2805]])

In [24]:
decrypt_con_modulo = sp.Matrix(np.dot(modulo_inversa, mensaje_encriptado_mod)%modulo)

sp.Matrix(decrypt_con_modulo)

Matrix([
[66,  7, 41, 38, 27, 65, 58, 59,  2, 56, 39, 41, 58, 31, 45, 46, 53, 45, 60, 58,  4, 45, 42],
[31, 44, 41, 58, 43, 47, 31, 58, 46, 41, 30, 41, 58, 31, 45, 46, 54, 58, 28, 35, 31, 40, 61],
[58, 66,  3, 35, 45, 32, 44, 47, 46, 27, 58, 46, 47, 58, 30, 55, 27, 58, 51, 58, 45, 35, 33],
[47, 31, 58, 27, 30, 31, 38, 27, 40, 46, 31, 58, 29, 41, 40, 58, 53, 40, 35, 39, 41, 65, 58]])

Comparemos el mensaje vectorizado con el mensaje desencriptado.

In [25]:
mensaje_vectorizado

Matrix([
[66,  7, 41, 38, 27, 65, 58, 59,  2, 56, 39, 41, 58, 31, 45, 46, 53, 45, 60, 58,  4, 45, 42],
[31, 44, 41, 58, 43, 47, 31, 58, 46, 41, 30, 41, 58, 31, 45, 46, 54, 58, 28, 35, 31, 40, 61],
[58, 66,  3, 35, 45, 32, 44, 47, 46, 27, 58, 46, 47, 58, 30, 55, 27, 58, 51, 58, 45, 35, 33],
[47, 31, 58, 27, 30, 31, 38, 27, 40, 46, 31, 58, 29, 41, 40, 58, 53, 40, 35, 39, 41, 65, 58]])

In [26]:
decrypt_con_modulo

Matrix([
[66,  7, 41, 38, 27, 65, 58, 59,  2, 56, 39, 41, 58, 31, 45, 46, 53, 45, 60, 58,  4, 45, 42],
[31, 44, 41, 58, 43, 47, 31, 58, 46, 41, 30, 41, 58, 31, 45, 46, 54, 58, 28, 35, 31, 40, 61],
[58, 66,  3, 35, 45, 32, 44, 47, 46, 27, 58, 46, 47, 58, 30, 55, 27, 58, 51, 58, 45, 35, 33],
[47, 31, 58, 27, 30, 31, 38, 27, 40, 46, 31, 58, 29, 41, 40, 58, 53, 40, 35, 39, 41, 65, 58]])

#### El mensaje desencriptado, es exactamente igual a el mensaje vectorizado??

In [27]:
# Aquí nos damos cuenta con un booleano
decrypt_con_modulo == mensaje_vectorizado

True

In [28]:
numpy_array = []
for i in decrypt_con_modulo:
  for key in indices_dict:
    if i == indices_dict[key]:
      numpy_array.append(key)

numpy_array = np.array(numpy_array).reshape(matriz_sp.shape[0], -1)
numpy_array

array([['¡', 'H', 'o', 'l', 'a', '!', ' ', '¿', 'C', 'ó', 'm', 'o', ' ',
        'e', 's', 't', 'á', 's', '?', ' ', 'E', 's', 'p'],
       ['e', 'r', 'o', ' ', 'q', 'u', 'e', ' ', 't', 'o', 'd', 'o', ' ',
        'e', 's', 't', 'é', ' ', 'b', 'i', 'e', 'n', '.'],
       [' ', '¡', 'D', 'i', 's', 'f', 'r', 'u', 't', 'a', ' ', 't', 'u',
        ' ', 'd', 'í', 'a', ' ', 'y', ' ', 's', 'i', 'g'],
       ['u', 'e', ' ', 'a', 'd', 'e', 'l', 'a', 'n', 't', 'e', ' ', 'c',
        'o', 'n', ' ', 'á', 'n', 'i', 'm', 'o', '!', ' ']], dtype='<U1')

### Ahora mostremos el mensaje de forma alfabetica.

In [43]:
def mostrar_mensaje(mensaje_a_mostrar):
  cadena_salida = [];
  for decrypt in decrypt_con_modulo:
    for key, value in indices_dict.items():
      if decrypt == value:
        cadena_salida.append(key);


  return "".join(cadena_salida)


cadena_salida = mostrar_mensaje(decrypt_con_modulo)
print(cadena_salida)

¡Hola! ¿Cómo estás? Espero que todo esté bien. ¡Disfruta tu día y sigue adelante con ánimo! 
